services:
  ms-producto:
    build:
      context: .
    image: ms-producto:v1.0
    container_name: producto_service
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=ecomercedb
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ecomercedb:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    restart: always
    volumes:
      - ./src:/app
    networks:
      - red1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-producto.rule=Host(`producto.localhost`) && PathPrefix(`/api/v1`)"
      - "traefik.http.services.ms-producto.loadbalancer.server.port=5003"
    deploy: 
      replicas: 1
networks:
  red1:
    external: true
