services:
  ms-compras:
    build:
      context: .
    image: ms-compras:v1.2
    environment:
      - FLASK_ENV=${FLASK_ENV} 

      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=ecomercedb
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ecomercedb:${POSTGRES_PORT}/${POSTGRES_DB}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env
    restart: always
    volumes:
      - ./src:/app 
    networks:
      - e_comerce_red1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-compras.rule=Host(`compras.localhost`) && PathPrefix(`/api/v1`)"
      - "traefik.http.services.ms-compras.loadbalancer.server.port=5000"
    deploy: 
      replicas: 1

networks:
  e_comerce_red1:
    external: true
