services:
  ms-orquestador:
    build: .
    container_name: ms-orquestador
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=${FLASK_ENV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=ecomercedb
      - POSTGRES_PORT=${POSTGRES_PORT}
      
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ecomercedb:${POSTGRES_PORT}/${POSTGRES_DB}
      
      - PAGOS_URL=http://pagos_service:5002/api/v1/pagos
      - STOCK_URL=http://stock_service:5001/api/v1/stock
      - PRODUCTO_URL=http://producto_service:5003/api/v1/producto
      - COMPRAS_URL=http://ms-compras:5000/api/v1/compra

      - REDIS_HOST=redis_service
      - REDIS_PORT=6379
    env_file:
      - .env
    ports:
      - "5005:5005"
    networks:
      - red1

networks:
  red1:
    external: true